### PR TITLE
feed+route+model: feed endpoint

### PR DESCRIPTION
**Pull request by willeponken**

### CODE REVIEW

**Comment by willeponken** [comment]
2018-12-13-140352_668x166_scrot

**Comment by Hjortsberg** [comment]
> 
> 
> 2018-12-13-140352_668x166_scrot

WHAT IN THE WORLD HAVE YOU DONE!? That's fokkin splendid m8!

**Comment by willeponken** [comment]
LUUUUUUUUUUUUUUUUUUUUUUUUUUUURAAAAAAAAAAAAAAAAAAAAAAAAAAAD

**Comment by willeponken** [comment]
> Overall coverage decreased (-12.6%) to 12.164% :sob:

**Pull request merged**
