### PR TITLE
purge the javascript (fixes: #103)

### PR DESCRIPTION
**Pull request by Hjortsberg**
This commit has converted the last (?) .js files to .ts.

### CODE REVIEW

**Comment by willeponken** [comment]
Why hasn't this been merged yet?

**Comment by Hjortsberg** [comment]
It still doesn't deploy! WHAT?!

**Comment by willeponken** [comment]
Hahaha, looking at GitHub's status page, they "fixed" the problem one minute after your merge!

**Comment by Hjortsberg** [comment]
Just my luck 👍

**Pull request merged**
